import React, { useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import Section from '../components/common/Section';
import Button from '../components/common/Button';
import {
    User, Activity, FileText, Calendar, Pill,
    Thermometer, Heart, Beaker, Clock, ChevronLeft, Download
} from 'lucide-react';

const ResultPage = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const summary = location.state?.summary;

    useEffect(() => {
        if (!summary) {
            navigate('/');
        }
    }, [summary, navigate]);

    if (!summary) return null;

    const { patient_profile, sections, medications, timeline, lab_data } = summary;

    // Safely parse JSON if it's a string (though backend handles this now)
    // Note: In Hero.jsx response.data is passed, which is already an object if backend sends proper JSON.

    return (
        <div className="min-h-screen bg-gray-50 flex flex-col">
            <Navbar />

            <main className="flex-grow pt-24 pb-16">
                <Section>
                    <div className="max-w-6xl mx-auto space-y-8">

                        {/* Header & Actions */}
                        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                            <div>
                                <Button
                                    variant="outline"
                                    className="mb-4 text-sm py-1 px-3"
                                    onClick={() => navigate('/')}
                                >
                                    <ChevronLeft size={16} className="mr-1" /> Back to Upload
                                </Button>
                                <h1 className="text-3xl font-bold text-gray-900">Medical Summary Report</h1>
                                <p className="text-gray-500 mt-1">Generated by AI • Clinical Decision Support</p>
                            </div>
                            <Button variant="primary" onClick={() => window.print()}>
                                <Download size={18} className="mr-2" /> Export PDF
                            </Button>
                        </div>

                        {/* Patient Profile Card */}
                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-8">
                            <div className="flex items-center gap-3 mb-6">
                                <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                                    <User size={24} />
                                </div>
                                <h2 className="text-xl font-semibold text-gray-900">Patient Profile</h2>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                                <ProfileItem label="Name" value={patient_profile?.name} />
                                <ProfileItem label="Age/Gender" value={`${patient_profile?.age || '-'} / ${patient_profile?.gender || '-'}`} />
                                <ProfileItem label="Primary Diagnosis" value={patient_profile?.primary_diagnosis} highlight />
                                <ProfileItem label="Doctor" value={patient_profile?.doctor} />
                            </div>
                        </div>

                        {/* Vital Signs Grid */}
                        {sections?.vital_signs && (
                            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                                <VitalCard icon={Heart} label="Heart Rate" value={sections.vital_signs.hr} unit="bpm" color="red" />
                                <VitalCard icon={Activity} label="Blood Pressure" value={sections.vital_signs.bp} unit="mmHg" color="blue" />
                                <VitalCard icon={Thermometer} label="Temperature" value={sections.vital_signs.temp} unit="" color="orange" />
                                <VitalCard icon={Activity} label="SpO2" value={sections.vital_signs.spo2} unit="%" color="green" />
                                <VitalCard icon={Activity} label="Resp. Rate" value={sections.vital_signs.resp} unit="/min" color="purple" />
                            </div>
                        )}

                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            {/* Left Column: Clinical Details */}
                            <div className="lg:col-span-2 space-y-8">

                                {/* Chief Complaint & Diagnosis */}
                                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
                                            <FileText size={24} />
                                        </div>
                                        <h3 className="text-lg font-semibold text-gray-900">Clinical Overview</h3>
                                    </div>
                                    <div className="space-y-4">
                                        <div>
                                            <h4 className="text-sm font-medium text-gray-500 uppercase tracking-wide mb-1">Chief Complaint</h4>
                                            <p className="text-gray-800 leading-relaxed">{sections?.chief_complaint || 'N/A'}</p>
                                        </div>
                                        <div className="h-px bg-gray-100 my-4" />
                                        <div>
                                            <h4 className="text-sm font-medium text-gray-500 uppercase tracking-wide mb-1">Diagnosis Details</h4>
                                            <p className="text-gray-800 leading-relaxed">{sections?.diagnosis_details || 'N/A'}</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Key Findings */}
                                {sections?.key_findings?.length > 0 && (
                                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="p-2 bg-yellow-50 text-yellow-600 rounded-lg">
                                                <Activity size={24} />
                                            </div>
                                            <h3 className="text-lg font-semibold text-gray-900">Key Findings</h3>
                                        </div>
                                        <ul className="space-y-3">
                                            {sections.key_findings.map((item, idx) => (
                                                <li key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-gray-50">
                                                    <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-white text-xs font-bold text-gray-500 rounded-full border border-gray-200">
                                                        {item.page || '?'}
                                                    </span>
                                                    <p className="text-gray-700">{item.text}</p>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}

                                {/* Treatment Plan */}
                                {sections?.treatment_plan?.length > 0 && (
                                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
                                                <CheckCircle size={24} />
                                            </div>
                                            <h3 className="text-lg font-semibold text-gray-900">Treatment Plan</h3>
                                        </div>
                                        <div className="bg-emerald-50/50 rounded-xl p-5 border border-emerald-100">
                                            <ul className="space-y-2">
                                                {sections.treatment_plan.map((item, idx) => (
                                                    <li key={idx} className="flex items-start gap-2 text-gray-800">
                                                        <span className="text-emerald-500 mt-1.5">•</span>
                                                        <span>{item}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Right Column: Meds, Labs, Timeline */}
                            <div className="space-y-8">

                                {/* Medications */}
                                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="p-2 bg-pink-50 text-pink-600 rounded-lg">
                                            <Pill size={24} />
                                        </div>
                                        <h3 className="text-lg font-semibold text-gray-900">Medications</h3>
                                    </div>
                                    {medications?.length > 0 ? (
                                        <div className="space-y-3">
                                            {medications.map((med, idx) => (
                                                <div key={idx} className="p-3 border border-gray-100 rounded-xl hover:bg-gray-50 transition-colors">
                                                    <div className="font-medium text-gray-900">{med.name}</div>
                                                    <div className="text-sm text-gray-500 mt-1">
                                                        {med.dose} • {med.frequency}
                                                    </div>
                                                    {med.type && (
                                                        <span className="inline-block mt-2 text-xs font-medium px-2 py-0.5 bg-gray-100 text-gray-600 rounded-full">
                                                            {med.type}
                                                        </span>
                                                    )}
                                                </div>
                                            ))}
                                        </div>
                                    ) : (
                                        <p className="text-gray-500 text-sm">No medications listed.</p>
                                    )}
                                </div>

                                {/* Lab Data */}
                                {lab_data?.length > 0 && (
                                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="p-2 bg-purple-50 text-purple-600 rounded-lg">
                                                <Beaker size={24} />
                                            </div>
                                            <h3 className="text-lg font-semibold text-gray-900">Lab Data</h3>
                                        </div>
                                        <div className="overflow-x-auto">
                                            <table className="w-full text-sm text-left">
                                                <thead className="text-xs text-gray-500 uppercase bg-gray-50">
                                                    <tr>
                                                        <th className="px-3 py-2 rounded-l-lg">Test</th>
                                                        <th className="px-3 py-2">Value</th>
                                                        <th className="px-3 py-2 rounded-r-lg">Unit</th>
                                                    </tr>
                                                </thead>
                                                <tbody className="divide-y divide-gray-100">
                                                    {lab_data.map((lab, idx) => (
                                                        <tr key={idx}>
                                                            <td className="px-3 py-2 font-medium text-gray-900">{lab.test_name}</td>
                                                            <td className="px-3 py-2">{lab.value}</td>
                                                            <td className="px-3 py-2 text-gray-500">{lab.unit}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                )}

                                {/* Timeline */}
                                {timeline?.length > 0 && (
                                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="p-2 bg-teal-50 text-teal-600 rounded-lg">
                                                <Clock size={24} />
                                            </div>
                                            <h3 className="text-lg font-semibold text-gray-900">Timeline</h3>
                                        </div>
                                        <div className="relative border-l-2 border-gray-100 ml-3 space-y-6 py-2">
                                            {timeline.map((event, idx) => (
                                                <div key={idx} className="ml-6 relative">
                                                    <div className="absolute -left-[31px] top-1.5 w-4 h-4 rounded-full border-2 border-white bg-teal-400 shadow-sm" />
                                                    <time className="text-xs font-semibold text-teal-600 uppercase tracking-wide">
                                                        {event.date}
                                                    </time>
                                                    <p className="text-sm text-gray-700 mt-0.5">{event.event}</p>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </Section>
            </main>
            <Footer />
        </div>
    );
};

const ProfileItem = ({ label, value, highlight }) => (
    <div className={`flex flex-col ${highlight ? 'col-span-1 md:col-span-2' : ''}`}>
        <span className="text-xs font-medium text-gray-400 uppercase tracking-wider mb-1">{label}</span>
        <span className={`text-lg font-medium ${highlight ? 'text-primary-600' : 'text-gray-900'}`}>
            {value || 'N/A'}
        </span>
    </div>
);

const VitalCard = ({ icon: Icon, label, value, unit, color }) => {
    const colorClasses = {
        red: 'bg-red-50 text-red-600',
        blue: 'bg-blue-50 text-blue-600',
        orange: 'bg-orange-50 text-orange-600',
        green: 'bg-green-50 text-green-600',
        purple: 'bg-purple-50 text-purple-600',
    };

    return (
        <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm flex flex-col items-center text-center hover:shadow-md transition-shadow">
            <div className={`p-2 rounded-lg mb-2 ${colorClasses[color] || 'bg-gray-100'}`}>
                <Icon size={20} />
            </div>
            <span className="text-xs text-gray-400 font-medium uppercase">{label}</span>
            <div className="mt-1">
                <span className="text-xl font-bold text-gray-900">{value || '-'}</span>
                {unit && <span className="text-xs text-gray-500 ml-0.5">{unit}</span>}
            </div>
        </div>
    );
};

// Check circle icon was just a placeholder
const CheckCircle = ({ size, className }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={className}
    >
        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
        <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
);

export default ResultPage;
